### ISSUE TITLE
Is this active?

### ISSUE THREAD

**Issue by mightyiam** [erikdesjardins/babel-plugin-transform-dead-code-elimination#12]
Or is everyone moving to Webpack?

**Comment by mightyiam** [comment]
Oh, I'm figuring out that tree shaking is not yet a widely performed activity.

**Comment by mightyiam** [comment]
Anyway, I'm getting a bug with the latest npm release of this. Should I report it?

**Comment by erikdesjardins** [comment]
I'm not actively developing it, it pretty much only exists as a direct port from Babel 5 to Babel 6. But I will fix bugs when I have time -- probably this weekend.

I'm hoping that Webpack 2 will make this unnecessary! (whenever it's out of beta)

**Comment by mightyiam** [comment]
But I love Browserify!

**Comment by hzoo** [comment]
@erikdesjardins FYI, there's a babel 6 version of this (hopefully open sourcing soon) with some other minification plugins

**Comment by erikdesjardins** [comment]
Neat -- supported by the Babel team? If so, do you want ownership of the package? I kinda stole the good name :sweat_smile:

**Comment by hzoo** [comment]
Yeah would be under the babel org. I think it's different but I'l let you know otherwise

**Comment by mightyiam** [comment]
Any update, please?

**Comment by erikdesjardins** [comment]
This is super stale by now, but https://github.com/babel/minify

**Comment by hzoo** [comment]
aside: I thought I invited you to the Babel org a while ago @erikdesjardins 😄 , dono if you'd be interested in contributing more

**Comment by erikdesjardins** [comment]
@hzoo hmm I probably won't have much free time until next year, so I don't know if you wanna do it until then, but I'd be honoured! (there are def a few things that I'd be interested in contributing to ~~babili~~babel-minify...when I finally have time) 😁
